name: "Build and Test"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-on-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsodium-dev
      - name: "Build and Test"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          make
          ./test_hkdf_hmacsha512